export const runtime = 'edge';
import { NextRequest, NextResponse } from "next/server";
import { db } from "@/src/lib/firebase";
import { collection, addDoc, Timestamp, getDocs } from "firebase/firestore";
import { encode } from "ngeohash";
import { Store } from "@/types/store";

// POST: 店舗データを保存
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { name, videoUrl, lat, lng, address, prefecture, category } = body;

    // バリデーション
    if (!name || typeof lat !== "number" || typeof lng !== "number") {
      return NextResponse.json(
        { error: "店名、緯度、経度は必須です" },
        { status: 400 }
      );
    }

    // geohashを生成（精度レベル9を推奨）
    const geohash = encode(lat, lng, 9);

    // placeIdを生成（geohash + timestampの一部を使用）
    const placeId = `place_${geohash}_${Date.now()}`;

    // 現在時刻
    const now = Timestamp.now();

    // アフィリエイトリンクを自動生成
    // 香川県の例: 緯度経度を使用して検索URLを生成
    const hotelSearchUrl = `https://www.google.com/travel/hotels?q=${lat},${lng}`;
    const rentacarUrl = `https://www.google.com/travel/cars?q=${address || prefecture}`;

    // Storeデータを作成
    const storeData = {
      placeId,
      name,
      lat,
      lng,
      geohash,
      region: "shikoku" as const,
      prefecture: prefecture || "kagawa",
      category: category || "gourmet",
      postCount: videoUrl ? 1 : 0, // 動画URLがあれば投稿数1、なければ0
      createdAt: now,
      updatedAt: now,
      affiliateLinks: {
        hotelSearchUrl,
        rentacarUrl,
      },
      lastScrapedAt: now,
      isAutoGenerated: false, // 管理画面から手動登録なのでfalse
    };

    // Firestoreに保存
    const storesCollection = collection(db, "stores");
    const docRef = await addDoc(storesCollection, storeData);

    // YouTube動画URLがある場合は、postsコレクションにも保存
    if (videoUrl) {
      // YouTube動画IDを抽出（簡単なパターンマッチ）
      let videoId = "";
      const youtubeMatch = videoUrl.match(
        /(?:youtube\.com\/watch\?v=|youtu\.be\/)([^&\n?#]+)/
      );
      if (youtubeMatch) {
        videoId = youtubeMatch[1];
      }

      const postsCollection = collection(db, "posts");
      await addDoc(postsCollection, {
        storeId: docRef.id,
        platform: "youtube" as const,
        url: videoUrl,
        title: `${name} - YouTube動画`,
        status: "auto" as const,
        createdAt: now,
      });
    }

    return NextResponse.json(
      {
        success: true,
        id: docRef.id,
        geohash,
        message: "店舗データを保存しました",
      },
      { status: 200 }
    );
  } catch (error) {
    console.error("Error saving store:", error);
    return NextResponse.json(
      {
        error:
          error instanceof Error
            ? error.message
            : "店舗データの保存に失敗しました",
      },
      { status: 500 }
    );
  }
}

// GET: 全店舗データを取得
export async function GET() {
  try {
    const storesCollection = collection(db, "stores");
    const snapshot = await getDocs(storesCollection);
    const stores = snapshot.docs.map((doc) => ({
      id: doc.id,
      ...doc.data(),
    })) as (Store & { id: string })[];

    // TimestampをJSONに変換
    const storesWithJsonTimestamps = stores.map((store) => ({
      ...store,
      createdAt: store.createdAt.toMillis(),
      updatedAt: store.updatedAt.toMillis(),
      lastScrapedAt: store.lastScrapedAt.toMillis(),
    }));

    return NextResponse.json({ stores: storesWithJsonTimestamps }, { status: 200 });
  } catch (error) {
    console.error("Error fetching stores:", error);
    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : "店舗データの取得に失敗しました",
      },
      { status: 500 }
    );
  }
}
