import { Timestamp } from "firebase/firestore";

export type Prefecture = "kagawa" | "ehime" | "kochi" | "tokushima";
export type Category = "gourmet" | "tourism" | "onsen" | "spot";

export interface Store {
  placeId: string;
  name: string;
  lat: number;
  lng: number;
  geohash: string; // Phase 1 から必須（後方互換性のため）
  region: "shikoku";
  prefecture: Prefecture;
  category: Category;
  subCategory?: string;
  postCount: number;
  createdAt: Timestamp;
  updatedAt: Timestamp;
  affiliateLinks: {
    hotelSearchUrl?: string;
    rentacarUrl?: string;
    manualHotelUrl?: string; // Phase 2 で使用
  };
  lastScrapedAt: Timestamp;
  isAutoGenerated: boolean;
}