"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import LazyMap from "@/components/LazyMap";

interface Store {
  id: string;
  placeId: string;
  name: string;
  lat: number;
  lng: number;
  geohash: string;
  region: "shikoku";
  prefecture: "kagawa" | "ehime" | "kochi" | "tokushima";
  category: "gourmet" | "tourism" | "onsen" | "spot";
  subCategory?: string;
  postCount: number;
  createdAt: number;
  updatedAt: number;
  affiliateLinks: {
    hotelSearchUrl?: string;
    rentacarUrl?: string;
    manualHotelUrl?: string;
  };
  lastScrapedAt: number;
  isAutoGenerated: boolean;
}

interface Post {
  id: string;
  storeId: string;
  platform: "youtube";
  url: string;
  title?: string;
  text?: string;
  status: "auto" | "pending" | "rejected";
  createdAt: number;
}

export default function Home() {
  const [stores, setStores] = useState<Store[]>([]);
  const [posts, setPosts] = useState<Post[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        // 店舗データを取得
        const storesResponse = await fetch("/api/stores");
        if (!storesResponse.ok) {
          throw new Error("店舗データの取得に失敗しました");
        }
        const storesData = await storesResponse.json();
        setStores(storesData.stores || []);

        // 投稿データを取得
        const postsResponse = await fetch("/api/posts");
        if (postsResponse.ok) {
          const postsData = await postsResponse.json();
          setPosts(postsData.posts || []);
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : "データの取得に失敗しました");
        console.error("Error fetching data:", err);
      } finally {
        setLoading(false);
      }
    };

    fetchData();
  }, []);

  return (
    <main className="h-screen w-screen overflow-hidden flex flex-col">
      {/* 最小限のヘッダー */}
      <header className="bg-white/95 backdrop-blur-sm shadow-sm border-b z-10 flex-shrink-0">
        <div className="px-4 py-2">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-lg font-bold text-gray-900">
                四国SNS飲食店マップ
              </h1>
            </div>
            <div className="flex items-center gap-2">
              {!loading && !error && stores.length > 0 && (
                <span className="text-xs text-gray-600">
                  店舗数: {stores.length}件
                </span>
              )}
              <Link
                href="/admin"
                className="px-3 py-1.5 bg-blue-600 text-white rounded-md hover:bg-blue-700 transition-colors text-sm"
              >
                管理画面
              </Link>
            </div>
          </div>
        </div>
      </header>

      {/* 全画面地図 */}
      <div className="flex-1 relative min-h-0">
        {loading ? (
          <div className="absolute inset-0 flex items-center justify-center bg-gray-50">
            <div className="text-center">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto mb-4"></div>
              <p className="text-gray-600">データを読み込んでいます...</p>
            </div>
          </div>
        ) : error ? (
          <div className="absolute inset-0 flex items-center justify-center bg-gray-50">
            <div className="text-center">
              <p className="text-red-600 mb-4">{error}</p>
              <button
                onClick={() => window.location.reload()}
                className="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
              >
                再読み込み
              </button>
            </div>
          </div>
        ) : (
          <div className="absolute inset-0">
            <LazyMap stores={stores as any} posts={posts as any} />
          </div>
        )}
      </div>
    </main>
  );
}